import type { Rule } from '../types.js';
export declare const nnbSu: Rule;
export declare const nnbSuBakke: Rule;
export declare const nnbGeot: Rule;
export declare const nnbGeo: Rule;
export declare const nnbGeonde: Rule;
export declare const nnbMankeum: Rule;
export declare const nnbDaero: Rule;
export declare const nnbPpun: Rule;
export declare const nnbGyeom: Rule;
export declare const nnbManTime: Rule;
export declare const nnbRi: Rule;
export declare const nnbTende: Rule;
export declare const nnbBa: Rule;
export declare const nnbChae: Rule;
export declare const nnbJul: Rule;
export declare const nnbTtaemun: Rule;
export declare const nnbJung: Rule;
export declare const nnbJeok: Rule;
export declare const nnbGim: Rule;
export declare const spacingRules: Rule[];
//# sourceMappingURL=spacing.d.ts.map